services:
  hueget:
    build:
      context: .
    container_name: sendmailx
    ports:
      - "3100:3100"
    environment:
      HUE_BRIDGE_IP: "yourPhilipsHueBridgeIpAddress" # Replace with your Philips Hue bridge IP address
      HUE_USERNAME: "yourPhilipsHueApiUsername" # Replace with your Philips Hue api username
    restart: unless-stopped